README.md
=> updated maesh readme.md

.github/workflows/ci.yml
Fixes https://github.com/layer5io/meshery/issues/362
=> Fixed #362 Switch to the new Docker Github action in Meshery-maesh repo

README.md
Fix logo and badges hyperlinks.
Fixed issue from #16
=> Fix badges hyperlinks

README.md
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>
=> #18 old logo is updated

README.md, maesh/client.go, maesh/install-maesh.go, maesh/maesh.go, maesh/vet.go, maesh/yaml.go, main.go
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>
=> lint issue is resolved

README.md
Signed-off-by: ashiscs <ashissingh640@gmail.com>
=> added dynamic slack badge and CII badge

.github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/question.md
fixes #24 
Signed-off-by: ashiscs <ashissingh640@gmail.com>
=> added missing templates

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Signed-off-by: jomefavourite <jfjomefavourite@gmail.com>
=> added release drafter files #43

.github/workflows/slack.yml
Fixed the slack notification on repo stars count
fix #54 
Signed-off-by: Arunagirinadan Sudharshan <sudhan.aruna.97@gmail.com>
=> CI: Fixed the slack notification on repo stars count

Dockerfile
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>
This PR fixes #66.
This Dockerfile is taken from https://github.com/layer5io/meshery-istio with slight modifications.
=> Move to distroless image

README.md
=> [README] Community section updates

.github/workflows/slack.yml
Signed-off-by: debjani1413 <deydebjani916@gmail.com>
Description
Updated the link in slack.yml from layer5io to meshery
=> Updated  the slack.yml

internal/config/config.go
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
=> [chore] make traefik_mesh installation operation name compliant with SMP protos

.github/workflows/build-and-release.yml, .github/workflows/ci.yml, Dockerfile
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>**Description**
=> [build] nodejs compatible base container img

.github/install/deploy.yaml, .github/workflows/e2etest.yaml
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Added e2e test

.github/workflows/e2etest.yaml, README.md
This PR has an incomplete definition of e2e tests.
=> [CI] End-to-end test iniatlization

.github/workflows/newcomers.yml, .github/workflows/slack.yml
=> Updated slack.yml and added newcomers.yml to workflows folder

.github/workflows/e2etest.yaml
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
This PR updates e2etest.yaml for the traefik-mesh adapter
- Added the missing test assertions
- Added some missing steps and arguments
- Aligned the jobs properly
This PR fixes #139
=> [Cl] Update e2etest.yaml

.github/dependabot.yml
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Add Ashish and Rudraksh in reviewers

.github/dependabot.yml
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Remove Rudraksh from dependabot alerts

Dockerfile
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Upgrade go version

.github/workflows/e2etest.yaml
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>
Should fix the build fail.
=> fix build fail

traefik/error.go
=> Error description

.github/workflows/build-and-release.yml, .github/workflows/ci.yml, .github/workflows/error-ref-publisher.yaml
=> update versions in workflow

.github/workflows/e2etest.yaml
Signed-off-by: Axit Patel <patelakshit2025@gmail.com>
This PR is a part of  https://github.com/meshery/meshery/issues/5529
Ports the Cilium to the new core e2e workflow
=> [CI] Updated core workflow for E2E

Dockerfile
Signed-off-by: Lee Calcote <leecalcote@gmail.com>
This PR removes an unused component that was discussed on today's Meshery CI meeting.
=> Remove kubeopenapijson

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
=> Change Issue template to add adapter spreadsheet

.github/install/deploy.yaml, .github/workflows/e2etest.yaml, go.mod, go.sum, templates/oam/workloads/v1.4.5/traefikmesh.meshery.layer5io.schema.json, templates/oam/workloads/v1.4.5/traefikmesh_definition.json, templates/oam/workloads/v1.4.7/traefikmesh.meshery.layer5io.schema.json, templates/oam/workloads/v1.4.7/traefikmesh_definition.json, traefik/oam.go
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
=> Remove "Meshery" version from core components

go.mod, go.sum
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
=> upgrade meshkit

go.mod, go.sum, main.go, traefik/oam.go, traefik/traefik.go
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
=> Add Event streamer struct

Makefile, build/Makefile.core.mk, build/Makefile.show-help.mk
Signed-off-by: leecalcote <leecalcote@gmail.com>
=> [CI] Makefile improvement and Dockerfile update

.github/workflows/multi-platform.yml
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
This PR:
related to: https://github.com/meshery/meshery/issues/6245
=> [chore] Update build files

go.mod, go.sum
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
=> [chore] Upgrade meshkit and meshery-adapter-library

Makefile, build/Makefile.core.mk
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
This PR relaxes Go requirement.
=> Relax go req

.github/install/deploy.yaml
=> Update deploy.yaml with meshmodel required fields

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Signed-off-by: Xiao Ran <xiaor2@illinois.edu>
=> Fixed the link.
